# fly.toml app configuration file generated for prod-dobermann-webapp on 2023-12-01T17:09:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prod-dobermann-webapp"
primary_region = "lhr"

[build]
  dockerfile = "./Dockerfile"

[build.args]
  NEXT_PUBLIC_API_ARG = "https://api.dobermann.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
