name: deploy-staging
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      PAT:
        required: true
      FLY_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: refs/tags/v${{ inputs.version }}

      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging
        run: npm run deploy:stg
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
